use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // Marketplace : petites annonces de matos entre membres.
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("listings"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("user_id")).integer().not_null())
                    .col(ColumnDef::new(Alias::new("title")).string().not_null())
                    .col(ColumnDef::new(Alias::new("description")).string())
                    .col(ColumnDef::new(Alias::new("price_cents")).integer().not_null())
                    .col(ColumnDef::new(Alias::new("category")).string().not_null())
                    .col(ColumnDef::new(Alias::new("condition")).string().not_null())
                    .col(ColumnDef::new(Alias::new("city")).string())
                    .col(
                        ColumnDef::new(Alias::new("photos"))
                            .json()
                            .not_null()
                            .default("[]"),
                    )
                    .col(
                        ColumnDef::new(Alias::new("status"))
                            .string()
                            .not_null()
                            .default("active"),
                    )
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("updated_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_listings_status")
                    .table(Alias::new("listings"))
                    .col(Alias::new("status"))
                    .to_owned(),
            )
            .await?;

        // Offres : négociation d'un prix sur une annonce.
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("offers"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("listing_id")).integer().not_null())
                    .col(ColumnDef::new(Alias::new("user_id")).integer().not_null())
                    .col(ColumnDef::new(Alias::new("amount_cents")).integer().not_null())
                    .col(ColumnDef::new(Alias::new("message")).string())
                    .col(
                        ColumnDef::new(Alias::new("status"))
                            .string()
                            .not_null()
                            .default("pending"),
                    )
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_offers_listing")
                    .table(Alias::new("offers"))
                    .col(Alias::new("listing_id"))
                    .to_owned(),
            )
            .await?;

        // Sessions de bmx : rendez-vous entre membres (spot ou ville + horaire).
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("bmx_sessions"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("user_id")).integer().not_null())
                    .col(ColumnDef::new(Alias::new("title")).string().not_null())
                    .col(ColumnDef::new(Alias::new("description")).string())
                    .col(ColumnDef::new(Alias::new("city")).string())
                    .col(ColumnDef::new(Alias::new("spot_id")).integer())
                    .col(
                        ColumnDef::new(Alias::new("starts_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("session_members"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("session_id")).integer().not_null())
                    .col(ColumnDef::new(Alias::new("user_id")).integer().not_null())
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_session_members_unique")
                    .table(Alias::new("session_members"))
                    .col(Alias::new("session_id"))
                    .col(Alias::new("user_id"))
                    .unique()
                    .to_owned(),
            )
            .await?;

        // Annuaire des BMX shops (soumis par la communauté, modéré comme les spots).
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("shops"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("name")).string().not_null())
                    .col(ColumnDef::new(Alias::new("description")).string())
                    .col(ColumnDef::new(Alias::new("city")).string())
                    .col(ColumnDef::new(Alias::new("address")).string())
                    .col(ColumnDef::new(Alias::new("latitude")).double())
                    .col(ColumnDef::new(Alias::new("longitude")).double())
                    .col(ColumnDef::new(Alias::new("url")).string())
                    .col(ColumnDef::new(Alias::new("photo_url")).string())
                    .col(ColumnDef::new(Alias::new("submitted_by")).integer())
                    .col(
                        ColumnDef::new(Alias::new("approved"))
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("updated_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        for table in ["shops", "session_members", "bmx_sessions", "offers", "listings"] {
            manager
                .drop_table(Table::drop().table(Alias::new(table)).if_exists().to_owned())
                .await?;
        }
        Ok(())
    }
}
